FROM alpine:3.15

RUN apk add --no-cache ca-certificates curl tzdata

COPY astranet /usr/local/bin/

ARG UID=1000
ARG GID=1000
RUN adduser -D -u $UID -g $GID ast


ENV astDATA /home/ast/data
# this 777 will be replaced by 700 at runtime (allows semi-arbitrary "--user" values)
RUN mkdir -p "$astDATA" && chown -R ast:ast "$astDATA" && chmod 777 "$astDATA"
VOLUME /home/ast/data

USER ast
WORKDIR /home/ast

EXPOSE 20012 20013 20014 61015/udp 61016  6060
ENTRYPOINT ["astranet"]
