{
 "title": "N42 Internals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "query": "0.0,0.25,0.5, 0.9, 0.97, 0.99, 1"
   },
   { "name": "instance", "label": "instance", "query": { "query": "go_goroutines" } },
   {
    "name": "rate_interval",
    "label": "Rate Interval",
    "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Blocks execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Execution speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " ceil(increase(chain_execution_bucket{instance=~\"$instance\", le!=\"+Inf\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block insert speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " ceil(increase(chain_inserts_bucket{instance=~\"$instance\", le!=\"+Inf\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block validate speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " ceil(increase(chain_validation_bucket{instance=~\"$instance\", le!=\"+Inf\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block write speed ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": " ceil(increase(chain_write_bucket{instance=~\"$instance\", le!=\"+Inf\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Commit",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(db_commit_seconds_count{phase=\"total\",instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "commit: {{instance}}"
    }
   ]
  },
  {
   "title": "Commit speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_commit_seconds{phase=\"total\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "total: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc_wall_clock\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_wall_clock: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"write\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "write: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"sync\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "sync: {{instance}}"
    },
    {
     "expr": "db_gc_self_rtime_cpu{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_rtime_cpu: {{instance}}"
    },
    {
     "expr": "db_gc_work_rtime_cpu{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_rtime_cpu: {{instance}}"
    },
    {
     "expr": "db_gc_work_rtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_rtime: {{instance}}"
    },
    {
     "expr": "db_gc_self_rtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_rtime: {{instance}}"
    },
    {
     "expr": "db_commit_seconds{phase=\"gc_cpu_time\",quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_cpu_time: {{instance}}"
    },
    {
     "expr": "db_gc_self_xtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_self_xtime: {{instance}}"
    },
    {
     "expr": "db_gc_work_pnl_merge_time{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "work_pnl_merge_time: {{instance}}"
    },
    {
     "expr": "db_gc_slef_pnl_merge_time{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "self_pnl_merge_time: {{instance}}"
    },
    {
     "expr": "db_gc_work_xtime{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "gc_work_xtime: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "db_size{instance=~\"$instance\"}",
     "legendFormat": "size: {{instance}}"
    },
    {
     "expr": "db_mi_last_pgno{instance=~\"$instance\"}",
     "legendFormat": "db_mi_last_pgno: {{instance}}"
    }
   ]
  },
  {
   "title": "DB Pages Ops/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(db_pgops{phase=\"newly\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "newly: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"cow\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "cow: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"clone\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "clone: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"split\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "split: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"merge\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "merge: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"spill\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "spill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"wops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "wops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"unspill\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "unspill: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcrloops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcrloops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcwloops\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcwloops: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"gcxpages\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "gcxpages: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"msync\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "msync: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"fsync\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "fsync: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"minicore\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "minicore: {{instance}}"
    },
    {
     "expr": "rate(db_pgops{phase=\"prefault\", instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "prefault: {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "tx_limit{instance=~\"$instance\"}",
     "legendFormat": "limit: {{instance}}"
    },
    {
     "expr": "tx_dirty{instance=~\"$instance\"}",
     "legendFormat": "dirty: {{instance}}"
    }
   ]
  },
  {
   "title": "GC and State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "db_gc_leaf{instance=~\"$instance\"}",
     "legendFormat": "gc_leaf: {{instance}}"
    },
    {
     "expr": "db_gc_overflow{instance=~\"$instance\"}",
     "legendFormat": "gc_overflow: {{instance}}"
    },
    {
     "expr": "exec_steps_in_db{instance=~\"$instance\"}/100",
     "legendFormat": "exec_steps_in_db: {{instance}}"
    }
   ]
  },
  {
   "title": "getrusage: minflt - soft page faults (reclaims), majflt - hard faults",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_minor_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "soft: {{instance}}"
    },
    {
     "expr": "rate(process_major_pagefaults_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "hard: {{instance}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "mem: resident set size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident mem: {{instance}}"
    },
    {
     "expr": "mem_data{instance=~\"$instance\"}",
     "legendFormat": "data: {{instance}}"
    },
    {
     "expr": "mem_stack{instance=~\"$instance\"}",
     "legendFormat": "stack: {{instance}}"
    },
    {
     "expr": "mem_locked{instance=~\"$instance\"}",
     "legendFormat": "locked: {{instance}}"
    },
    {
     "expr": "mem_swap{instance=~\"$instance\"}",
     "legendFormat": "swap: {{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write syscall/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_io_write_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "in: {{instance}}"
    },
    {
     "expr": "rate(process_io_read_syscalls_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "out: {{instance}}"
    }
   ]
  },
  {
   "title": "cgo calls",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(go_cgo_calls_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "cgo_calls_count: {{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem: allocate objects/sec, free",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "memstats_mallocs_total: {{ instance }}"
    },
    {
     "expr": "rate(go_memstats_frees_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "memstats_frees_total: {{ instance }}"
    }
   ]
  },
  {
   "title": "Disk bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_io_storage_read_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "read: {{instance}}"
    },
    {
     "expr": "rate(process_io_storage_written_bytes_total{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "write: {{instance}}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "threads: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "increase(process_cpu_seconds_system_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "system: {{instance}}"
    },
    {
     "expr": "increase(process_cpu_seconds_user_total{instance=~\"$instance\"}[1m])",
     "legendFormat": "iowait: {{instance}}"
    }
   ]
  },
  {
   "title": "go memstat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=~\"$instance\"}",
     "legendFormat": "stack_inuse: {{ instance }}"
    },
    {
     "expr": "go_memstats_mspan_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mspan_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_mcache_sys_bytes{instance=~\"$instance\"}",
     "legendFormat": "mcache_sys: {{ instance }}"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=~\"$instance\"}",
     "legendFormat": "heap_alloc: {{ instance }}"
    }
   ]
  },
  {
   "title": "GC Stop the World per sec",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds{quantile=\"0.75\",instance=~\"$instance\"}[$rate_interval])"
    }
   ]
  },
  {
   "title": "TxPool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pool_process_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "process_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_add_remote_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "add_remote_txs: {{ instance }}"
    },
    {
     "expr": "pool_new_block{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "new_block: {{ instance }}"
    },
    {
     "expr": "pool_write_to_db{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "write_to_db: {{ instance }}"
    },
    {
     "expr": "pool_propagate_to_new_peer{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "propagate_to_new_peer: {{ instance }}"
    },
    {
     "expr": "pool_propagate_new_txs{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "propagate_new_txs: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(pool_process_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_process_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_add_remote_txs_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_add_remote_txs_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_new_block_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_new_block_count: {{ instance }}"
    },
    {
     "expr": "rate(pool_write_to_db_count{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_count: {{ instance }}"
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"txpool\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"txpool\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache rps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 62 },
   "targets": [
    {
     "expr": "rate(cache_total{name=\"txpool\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ result }}: {{ instance }} "
    },
    {
     "expr": "rate(cache_timeout_total{name=\"txpool\",instance=~\"$instance\"}[1m])",
     "legendFormat": "timeout: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"txpool\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"txpool\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    }
   ]
  },
  {
   "title": "DB",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pool_write_to_db_bytes{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "pool_write_to_db_bytes: {{ instance }}"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"success\"}[1m])",
     "legendFormat": "success {{ method }} {{ instance }} "
    },
    {
     "expr": "rate(rpc_duration_seconds_count{instance=~\"$instance\",success=\"failure\"}[1m])",
     "legendFormat": "failure {{ method }} {{ instance }} "
    }
   ]
  },
  {
   "title": "DB begin",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "db_begin_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": "db_begin_seconds: {{ method }} {{ instance }}"
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rpc_duration_seconds{quantile=\"$quantile\",instance=~\"$instance\"}",
     "legendFormat": " {{ method }} {{ instance }} {{ success }}"
    }
   ]
  },
  {
   "title": "GO Goroutines and Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=~\"$instance\"}",
     "legendFormat": "go/goroutines: {{instance}}"
    },
    {
     "expr": "go_threads{instance=~\"$instance\"}",
     "legendFormat": "go/threads: {{instance}}"
    }
   ]
  },
  {
   "title": "Cache keys",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cache_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "keys: {{ instance }} "
    },
    {
     "expr": "cache_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "list: {{ instance }} "
    },
    {
     "expr": "cache_code_keys_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_keys: {{ instance }} "
    },
    {
     "expr": "cache_code_list_total{name=\"rpc\",instance=~\"$instance\"}",
     "legendFormat": "code_list: {{ instance }} "
    }
   ]
  },
  {
   "title": "Cache hit-rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 91 },
   "targets": [
    {
     "expr": "sum(delta(cache_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "hit rate: {{ instance }} "
    },
    {
     "expr": "sum(delta(cache_code_total{result=\"hit\",name=\"rpc\",instance=~\"$instance\"}[1m]))/sum(delta(cache_code_total{name=\"rpc\",instance=~\"$instance\"}[1m])) ",
     "legendFormat": "code hit rate: {{ instance }} "
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=~\"$instance\"}[$rate_interval])",
     "legendFormat": "ingress: {{instance}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peer_count{instance=~\"$instance\"}",
     "legendFormat": "peers: {{instance}}-{{state}}"
    },
    {
     "expr": "rate(p2p_dials{instance=~\"$instance\"}[1m])",
     "legendFormat": "dials: {{instance}}"
    },
    {
     "expr": "rate(p2p_serves{instance=~\"$instance\"}[1m])",
     "legendFormat": "serves: {{instance}}"
    }
   ]
  }
 ]
}